AllCops:
  NewCops: enable
  SuggestExtensions: false
Layout/HeredocIndentation:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false
Naming/HeredocDelimiterNaming:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false # fixme: reenable
Naming/FileName:
  Enabled: false
Lint/RedundantStringCoercion:
  Enabled: false # fixme: reenable
Lint/DuplicateBranch:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Style/Documentation:
  Enabled: false # fixme: reenable
Metrics/BlockNesting:
  Max: 10
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: false
