name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: bundle install
    - run: bundle exec rake lint
    - run: bundle exec rake spec
    - run: bundle exec rake
    - run: node -v
    - run: npm -v
    - run: npm ci
    - run: npm t
    - uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: snapshots
        path: cypress/snapshots/**/*.png
    - uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: reports
        path: cypress/reports/**/*.*
